// Generated by CoffeeScript 1.12.6
module.exports = function(robot) {
  return robot.respond(/(.*)の天気は？/i, function(msg) {
    var basyo, city, request, weatherURL;
    basyo = msg.match[1];
    if (basyo === "埼玉") {
      city = 110010;
    } else if (basyo === "さいたま") {
      city = 110010;
    } else if (basyo === "東京") {
      city = 130010;
    } else if (basyo === "神奈川") {
      city = 140010;
    } else if (basyo === "千葉") {
      city = 120010;
    } else {
      city = 0;
    }
    weatherURL = 'http://weather.livedoor.com/forecast/webservice/json/v1?city=' + city;
    if (city === 0) {
      return msg.reply('その場所の天気はわかりません。');
    } else {
      request = msg.http(weatherURL).get();
    }
    return request(function(err, res, body) {
      var forecast, jtenki;
      jtenki = JSON.parse(body);
      forecast = jtenki.title + '予報だよぉ\r\n';
      forecast += '今日の天気は ' + jtenki['forecasts'][0]['telop'] + " でしょう\r\n";
      forecast += '明日の天気は ' + jtenki['forecasts'][1]['telop'] + " でしょう\r\n";
      forecast += '\r\n☆お天気概況☆\r\n';
      forecast += jtenki.description.text;
      return msg.reply(forecast);
    });
  });
};
